# Site settings
title: Things in a nutshell
author: quyenlv
author_avatar: http://www.gravatar.com/avatar/94018c93dd1592cf154971616f8f8ce2?s=50
email: gaimande@gmail.com
description: Things in a nutshell
baseurl: "" # optional
url: "https://quyenlv.github.io"
twitter_username: gaimande
github_username: quyenlv
github_repo: quyenlv/quyenlv.github.io
#google_analytics: UA-80085-YOUR-ID
# disqus: disqus-id

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap
